# Generated by Django 2.2.7 on 2019-11-24 08:28

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="customer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["first_name", "last_name", "phone_number"],
                name="main_custom_first_n_ddcaaf_gin",
            ),
        ),
    ]
