# Generated by Django 2.2.7 on 2019-11-24 08:28

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("main", "0001_initial")]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            sql=r"""CREATE INDEX "customer_admin_search" ON "main_customer" USING gin (
                      UPPER("first_name") gin_trgm_ops,
                      UPPER("last_name") gin_trgm_ops,
                      UPPER("phone_number") gin_trgm_ops
                );""",
            reverse_sql=r'DROP INDEX "customer_admin_search";',
        ),
    ]
